### ISSUE TITLE
Export training data export error "DataType"

### ISSUE THREAD

**Issue by jducnuigeen** [PUTvision/qgis-plugin-deepness#171]
Hello. I'm once again trying to export training data using the Deepness Training Data Export tool to detect building outlines in my aerial imagery. I've set my output directory path, and have my geotiff raster set in the "input layer" section, and the export image tiles option checked. I also have the Export segmentation mask for layer" option checked, and it points to a polygon shapefile of my building outlines labels seen in the imagery.
However, when I press export training data, I get this error:
![image](https://github.com/PUTvision/qgis-plugin-deepness/assets/25912064/b3b4abad-9b09-47f2-b069-04dea84ad47f)
Is this something to do with my input imagery or mask?
Thoughts?
(I'm using Deepness v 0.6.3)

**Comment by przemyslaw-aszkowski** [comment]
Hi, would it be possible for you to share the GeoTIFF and shapefile you used?

**Comment by jducnuigeen** [comment]
Sure, here are the image, and the shapefile with the building outlines.
Originally I thought the problem might be with my input imagery being too big, but the error still happens even with this much smaller imagery.
[two_tile_building_outlines.zip](https://github.com/PUTvision/qgis-plugin-deepness/files/15504885/two_tile_building_outlines.zip)
https://www.dropbox.com/scl/fi/byyktbtyfor6g4rw0iisf/two_tile_merged.zip?rlkey=boovewitk9ub2ghsyfcj9weyz&st=ps9lbg3i&dl=0

**Comment by przemyslaw-aszkowski** [comment]
Hi
I checked and there are two issues:
1) your geotiff is saved as Int32 data type
2) there is a bug in Deepness in handling such data type

Solution:
The bug is fixed on my branch (though it cannot be fully handled due to opencv library limitations). 

As a workaround before the fix is released, but also for your file size optimization, I recommend representing pixels as just uint8, it looks like it is possible to convert a tiff in QGIS (https://gis.stackexchange.com/questions/415458/changing-the-data-type-for-multiband-raster-file-to-integer). Once you have your tiff converted to uint8, you should be able to run it smoothly.

**Comment by jducnuigeen** [comment]
That's great, I really appreciate the fix and will adjust my images. Thank you !
