### ISSUE TITLE
non_max_suppression_fast raises an error.  

### ISSUE THREAD

**Issue by williamwalters** [PUTvision/qgis-plugin-deepness#75]
deepness\processing\models\detector.py", line 166, in postprocessing
pick_indxs = self.non_max_suppression_fast(outputs_x1y1x2y2, outputs_filtered[:, 4], self.iou_threshold)

TypeError: 'staticmethod' object is not callable

Removing the @staticmethod decorator fixed this although it may be needed for other uses?

**Comment by bartoszptak** [comment]
@williamwalters thank you for your issue! It was fixed in one of the latest PR - [https://github.com/PUTvision/qgis-plugin-deepness/pull/73/files#diff-31fce0a32dd3795b610090d00023ca848e275867408a195b9e47b9b378faa0cbL210](https://github.com/PUTvision/qgis-plugin-deepness/pull/73/files#diff-31fce0a32dd3795b610090d00023ca848e275867408a195b9e47b9b378faa0cbL210)

**Comment by williamwalters** [comment]
Awesome thank you!
