### ISSUE TITLE
Exporting training data error

### ISSUE THREAD

**Issue by jducnuigeen** [PUTvision/qgis-plugin-deepness#84]
Hello. I'm trying to export training data using the Deepness Training Data Export tool to detect building outlines in my aerial imagery. I've set my output directory path, and have my geotiff raster set in the "input layer" section, and the export image tiles option checked. I also have the Export segmentation mask for layer" option checked, and it points to a polygon shapefile of my building outlines labels seen in the imagery.
However, when I press export training data, I get this error:
![image](https://user-images.githubusercontent.com/25912064/230234196-ce89c384-9c5a-4e63-991b-639fb220fd44.png)
Any thoughts on where my problem exists?
I'd love to train my own model and share it openly with others, but I have a bit of work to do to train a model.

**Comment by przemyslaw-aszkowski** [comment]
Hi @jducnuigeen 
Thanks for your interest and for reporting this issue! You did everything correctly, as you described, but a bug entered the code during some refactorization. It is already fixed and will be available in the next release soon.

In the meantime, you can download the latest code from [here](https://github.com/PUTvision/qgis-plugin-deepness/suites/12134813801/artifacts/639794452), and install it from a zip file as described in [documentation](https://qgis-plugin-deepness.readthedocs.io/en/latest/main/main_installation.html). Hope everything will work now, otherwise please let me know :)

**Comment by przemyslaw-aszkowski** [comment]
Resolved in release 0.5.1
